import Foundation
import CryptoKit

/// Per-call packet encryption.
///
/// The relay forwards datagrams without being able to read them: the call key is
/// generated by the caller and handed to the callee over the TLS signaling
/// socket, never to the media relay. That keeps a rented Seoul box from being a
/// place where business calls sit in the clear.
///
/// ChaChaPoly rather than AES-GCM because it is constant-time in software and we
/// are sealing 50 small packets a second on a phone.
public struct CallSealedBox: Sendable {
    /// 12-byte nonce: 4-byte per-direction salt then an 8-byte counter. The salt
    /// differs per direction so the two ends can never collide on a nonce even
    /// though they share the key.
    public static let nonceSize = 12
    public static let tagSize = 16
}

public final class CallCrypto: @unchecked Sendable {
    public enum Direction: UInt32, Sendable {
        case callerToCallee = 0x0A0A_0A0A
        case calleeToCaller = 0x0B0B_0B0B

        var opposite: Direction {
            self == .callerToCallee ? .calleeToCaller : .callerToCallee
        }
    }

    private let key: SymmetricKey
    private let sendSalt: UInt32
    private let receiveSalt: UInt32
    private var sendCounter: UInt64 = 0
    private let lock = NSLock()

    /// 32-byte key, base64 encoded for the signaling payload.
    public static func generateKeyBase64() -> String {
        SymmetricKey(size: .bits256).withUnsafeBytes { Data($0).base64EncodedString() }
    }

    public init?(keyBase64: String, direction: Direction) {
        guard let raw = Data(base64Encoded: keyBase64), raw.count == 32 else { return nil }
        self.key = SymmetricKey(data: raw)
        // We stamp what we send with our own salt and only accept the other one.
        self.sendSalt = direction.rawValue
        self.receiveSalt = direction.opposite.rawValue
    }

    /// Sealed output is nonce ‖ ciphertext ‖ tag.
    public func seal(_ plaintext: Data) -> Data? {
        lock.lock()
        let counter = sendCounter
        sendCounter += 1
        lock.unlock()

        var nonceBytes = Data()
        nonceBytes.appendBigEndian(sendSalt)
        nonceBytes.appendBigEndian(counter)
        guard let nonce = try? ChaChaPoly.Nonce(data: nonceBytes),
              let sealed = try? ChaChaPoly.seal(plaintext, using: key, nonce: nonce) else {
            return nil
        }
        var out = nonceBytes
        out.append(sealed.ciphertext)
        out.append(sealed.tag)
        return out
    }

    public func open(_ envelope: Data) -> Data? {
        let minimum = CallSealedBox.nonceSize + CallSealedBox.tagSize
        guard envelope.count > minimum else { return nil }
        let bytes = [UInt8](envelope)

        // Reject anything not stamped with the peer's direction salt. Cheap guard
        // against our own packets being reflected back by a misconfigured relay.
        let salt = UInt32(bigEndian: bytes, at: 0)
        guard salt == receiveSalt else { return nil }

        let nonceData = envelope.prefix(CallSealedBox.nonceSize)
        let rest = envelope.dropFirst(CallSealedBox.nonceSize)
        let ciphertext = rest.prefix(rest.count - CallSealedBox.tagSize)
        let tag = rest.suffix(CallSealedBox.tagSize)

        guard let nonce = try? ChaChaPoly.Nonce(data: nonceData),
              let box = try? ChaChaPoly.SealedBox(nonce: nonce,
                                                  ciphertext: ciphertext,
                                                  tag: tag),
              let opened = try? ChaChaPoly.open(box, using: key) else {
            return nil
        }
        return opened
    }
}
